### ISSUE TITLE
Wrong unreadCount values coming from offline channel state

### ISSUE THREAD

**Issue by cvb941** [GetStream/stream-chat-android#4060]
**Describe the bug**
`client.state.channel("messaging", channelId).unreadCount`
This StateFlow<Int?> representing the count of unread messages in a channel sometimes produces values that jump around.

Scenario:
- Initial unread count is 5
- Upon receiving a new message, the count jumps from 5->6, then quickly back down to 6->5 and again to 5->6.

**SDK version**
- 5.8.0

**To Reproduce**
It seems like the underlying MutableStateFlow is being updated from multiple places, one of them likely being the standard observation and the second one from the **arriving push notification**?

The code lines in question:
https://github.com/GetStream/stream-chat-android/blob/ad5f2893f3dfb7d13e50e4b24969bda7fcf90617/stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImpl.kt#L182

This one seems suspicious due to applying +1 to the current value of unreadCount:
https://github.com/GetStream/stream-chat-android/blob/ad5f2893f3dfb7d13e50e4b24969bda7fcf90617/stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImpl.kt#L135

**Expected behavior**
The unreadCount number should be stable and hold the true current value of unread messages in a channel.

**Device:**
 - Vendor and model: Poco F4
 - Android version: 12

**Comment by leandroBorgesFerreira** [comment]
Hello @cvb941. I could reproduce this problem. We are working to fix this and I'll let you know as soon as it is ready.

**Comment by cvb941** [comment]
That's good to hear, thanks!

**Comment by leandroBorgesFerreira** [comment]
PR #4102 Fixes the loop in the sync for events that is causing the +1 unread count that you're experiencing. 

But we still need to make a refactor in this feature. It is currently not idempotent and results can vary if the message arrives before or after the sync of the SDK is ready. Another PR will be created to cover this case.

**Comment by adasiewiczr** [comment]
hey @cvb941,
we released a new version (5.10.0) that includes the fix. You can find more details [here](https://github.com/GetStream/stream-chat-android/releases/tag/v5.10.0).

**Comment by cvb941** [comment]
Hi, upon initial testing, the issue we had with the unread counts jumping around is still present. I will look into the issue more deeply again later and will let you know.
