### ISSUE TITLE
"Channel without name"

### ISSUE THREAD

**Issue by pixnbit** [GetStream/stream-chat-android#644]
Seeing this on the latest 4.3.0-beta-1, the channel list has 1:1 DM "Channel without name", they weren't setup named explicitly, but the title on the chat thread shows the correct name

![Screenshot_1600968476](https://user-images.githubusercontent.com/729730/94178941-a2c6d580-fe50-11ea-92c9-237b97bb665a.png)

![Screenshot_1600968433](https://user-images.githubusercontent.com/729730/94179023-c68a1b80-fe50-11ea-98af-8c607f0c462f.png)
![Screenshot_1600968081](https://user-images.githubusercontent.com/729730/94179041-cdb12980-fe50-11ea-925d-7e646bdadbb0.png)
![Screenshot_1600968075](https://user-images.githubusercontent.com/729730/94179057-d144b080-fe50-11ea-8162-1076a281e402.png)

**Comment by ogkuzmin** [comment]
Hello, @pixnbit!
Thank you very much for submitting this issue. We'll check and fix it!

**Comment by JcMinarro** [comment]
Hello @pixnbit 
We have done some improvement and this issue should be fixed on the last version.
Could you check it?

**Comment by beckmartin** [comment]
I still get this issue @JcMinarro on version 4.4.1 cc @ogkuzmin I am using databinding instead of viewbinding in my app, but this should not be the problem I guess.

**Comment by ogkuzmin** [comment]
@beckmartin Yes, we got this regression issue and fixed already, but we didn't release fixed version. I think new version with fix will be available this or next week

**Comment by beckmartin** [comment]
Thanks for the update, will keep an eye on this Thread

**Comment by beckmartin** [comment]
@ogkuzmin @JcMinarro We need this fixed for our production build, any updates when the fix will be released?

**Comment by ogkuzmin** [comment]
@beckmartin We have launched the new 4.4.2 with fix for that. Could you please check how it works for you?

**Comment by beckmartin** [comment]
It seems to be fixed now, Thank you!
