### ISSUE TITLE
Latest message not updating

### ISSUE THREAD

**Issue by pixnbit** [GetStream/stream-chat-android#698]
In the channel list, the latest message never updates in a same session. This is the latest 4.3.0-beta-6

![out](https://user-images.githubusercontent.com/729730/96186835-db5a4c00-0ef0-11eb-9010-06c699672b8c.gif)

**Comment by pixnbit** [comment]
Also you'll notice the black bold font for new messages never goes away, I think I reported in another ticket https://github.com/GetStream/stream-chat-android/issues/589

**Comment by tschellenbach** [comment]
Carter and I tried to replicate it, but no luck unfortunately. Can you give the 4.3.1-beta-1 release a try?

**Comment by tschellenbach** [comment]
the only way i was able to replicate it is if network is down/unavailable. It adds the message to local storage, but doesn't update the last message value you see in the channel list, is that the issue you're seeing?

**Comment by tschellenbach** [comment]
this was a tricky one, requires a patch in offline storage as well as the diff callback:
https://github.com/GetStream/stream-chat-android/pull/704

we'll get this merged early next week. note that this issue only happens when you are offline (at least in our testing it only happens while offline)

**Comment by pixnbit** [comment]
I can confirm the phone is online, and the other client connected has the new message showing up. 
Can the offline mode be disabled?

**Comment by tschellenbach** [comment]
I will update this ticket when the new version of the SDK becomes available.

**Comment by tschellenbach** [comment]
we didn't manage to ship the new release this week. should be live early next week

**Comment by JcMinarro** [comment]
Hello @pixnbit 

It has been fixed on the [last release](https://github.com/GetStream/stream-chat-android/releases/latest)
It should be working fine now

**Comment by pixnbit** [comment]
Thanks! Congrats on coming out of beta!

**Comment by pixnbit** [comment]
However the problem still persists in 4.4, I do see the mark read requests in the logcat:

> 2020-10-27 21:52:19.492 31310-31921/ai.zira.employee I/Chat:Events: {"type":"notification.mark_read","cid":"messaging:!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY","channel_id":"!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY","channel_type":"messaging","channel":{"id":"!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY","type":"messaging","cid":"messaging:!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY","last_message_at":"2020-10-19T18:08:22.587613Z","created_at":"2020-10-06T22:54:56.906116Z","updated_at":"2020-10-06T22:54:56.906116Z","created_by":null,"frozen":false,"member_count":2,"config":{"created_at":"2020-10-27T12:53:06.701038577Z","updated_at":"2020-10-27T12:53:06.701038754Z","name":"messaging","typing_events":true,"read_events":true,"connect_events":true,"search":true,"reactions":true,"replies":true,"mutes":true,"uploads":true,"url_enrichment":true,"message_retention":"infinite","max_message_length":5000,"automod":"disabled","automod_behavior":"flag","commands":[{"name":"giphy","description":"Post a random gif to the channel","args":"[text]","set":"fun_set"}]},"team":"enc-ZW5jLVZHMXdUbEJSUFQwPS1lbmM"},"user":{"id":"enc-ZW5jLVZGZHdibVZCUFQwPS1lbmM","role":"user","created_at":"2020-09-25T05:11:59.666842Z","updated_at":"2020-10-28T04:52:09.223126Z","last_active":"2020-10-28T04:45:47.969832Z","banned":false,"online":false,"teams":["enc-ZW5jLVZHMXdUbEJSUFQwPS1lbmM","enc-ZW5jLVZEQlNRbEJSUFQwPS1lbmM"],"devices":null,"image":"https://z-public-storage.s3.amazonaws.com/profile_pic/cd323a13-31a9-452f-ab12-15f629ea2a30.jpg","invisible":false,"name":"Xiachao Yang"},"created_at":"2020-10-28T04:52:20.268528687Z","unread_channels":0,"unread_count":0,"total_unread_count":0}
> 2020-10-27 21:52:19.493 31310-31662/ai.zira.employee I/Chat:Events: {"type":"notification.mark_read","cid":"messaging:!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY","channel_id":"!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY","channel_type":"messaging","channel":{"id":"!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY","type":"messaging","cid":"messaging:!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY","last_message_at":"2020-10-19T18:08:22.587613Z","created_at":"2020-10-06T22:54:56.906116Z","updated_at":"2020-10-06T22:54:56.906116Z","created_by":null,"frozen":false,"member_count":2,"config":{"created_at":"2020-10-27T12:53:06.701038577Z","updated_at":"2020-10-27T12:53:06.701038754Z","name":"messaging","typing_events":true,"read_events":true,"connect_events":true,"search":true,"reactions":true,"replies":true,"mutes":true,"uploads":true,"url_enrichment":true,"message_retention":"infinite","max_message_length":5000,"automod":"disabled","automod_behavior":"flag","commands":[{"name":"giphy","description":"Post a random gif to the channel","args":"[text]","set":"fun_set"}]},"team":"enc-ZW5jLVZHMXdUbEJSUFQwPS1lbmM"},"user":{"id":"enc-ZW5jLVZGZHdibVZCUFQwPS1lbmM","role":"user","created_at":"2020-09-25T05:11:59.666842Z","updated_at":"2020-10-28T04:52:09.223126Z","last_active":"2020-10-28T04:45:47.969832Z","banned":false,"online":false,"teams":["enc-ZW5jLVZHMXdUbEJSUFQwPS1lbmM","enc-ZW5jLVZEQlNRbEJSUFQwPS1lbmM"],"devices":null,"image":"https://z-public-storage.s3.amazonaws.com/profile_pic/cd323a13-31a9-452f-ab12-15f629ea2a30.jpg","invisible":false,"name":"Xiachao Yang"},"created_at":"2020-10-28T04:52:20.268528687Z","unread_count":0,"total_unread_count":0,"unread_channels":0}
> 2020-10-27 21:52:19.494 31310-32104/ai.zira.employee I/Chat:Http: <-- 201 Created https://chat-us-east-1.stream-io-api.com/channels/messaging/!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY/read?api_key=ke67tfdsr7cg&user_id=enc-ZW5jLVZGZHdibVZCUFQwPS1lbmM&client_id=f872ac0d-b501-419a-bc20-44c603ddbe2c (523ms)
> 2020-10-27 21:52:19.494 31310-32104/ai.zira.employee I/Chat:Http: Server: fasthttp
> 2020-10-27 21:52:19.494 31310-32104/ai.zira.employee I/Chat:Http: Date: Wed, 28 Oct 2020 04:52:20 GMT
> 2020-10-27 21:52:19.494 31310-32104/ai.zira.employee I/Chat:Http: Content-Type: application/json;charset=utf-8
> 2020-10-27 21:52:19.494 31310-32104/ai.zira.employee I/Chat:Http: Content-Length: 726
> 2020-10-27 21:52:19.494 31310-32104/ai.zira.employee I/Chat:Http: Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
> 2020-10-27 21:52:19.494 31310-32104/ai.zira.employee I/Chat:Http: X-Ratelimit-Remaining: 9999
> 2020-10-27 21:52:19.494 31310-32104/ai.zira.employee I/Chat:Http: X-Ratelimit-Reset: 1603860780
> 2020-10-27 21:52:19.494 31310-32104/ai.zira.employee I/Chat:Http: Access-Control-Allow-Origin: *
> 2020-10-27 21:52:19.494 31310-32104/ai.zira.employee I/Chat:Http: Access-Control-Max-Age: 86400
> 2020-10-27 21:52:19.494 31310-32104/ai.zira.employee I/Chat:Http: Access-Control-Allow-Headers: x-requested-with, content-type, accept, origin, authorization, x-csrftoken, x-stream-client, stream-auth-type, x-csrf-token
> 2020-10-27 21:52:19.494 31310-32104/ai.zira.employee I/Chat:Http: Cache-Control: no-cache
> 2020-10-27 21:52:19.494 31310-32104/ai.zira.employee I/Chat:Http: X-Ratelimit-Limit: 10000
> 2020-10-27 21:52:19.494 31310-32104/ai.zira.employee I/Chat:Http: Keep-Alive: timeout=58, max=1000
> 2020-10-27 21:52:19.494 31310-32104/ai.zira.employee I/Chat:Http: Connection: keep-alive
> 2020-10-27 21:52:19.495 31310-32104/ai.zira.employee I/Chat:Http: {"event":{"type":"message.read","cid":"messaging:!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY","channel_id":"!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY","channel_type":"messaging","user":{"id":"enc-ZW5jLVZGZHdibVZCUFQwPS1lbmM","role":"user","created_at":"2020-09-25T05:11:59.666842Z","updated_at":"2020-10-28T04:52:09.223126Z","last_active":"2020-10-28T04:45:47.969832Z","banned":false,"online":false,"teams":["enc-ZW5jLVZHMXdUbEJSUFQwPS1lbmM","enc-ZW5jLVZEQlNRbEJSUFQwPS1lbmM"],"name":"Xiachao Yang","devices":null,"image":"https://z-public-storage.s3.amazonaws.com/profile_pic/cd323a13-31a9-452f-ab12-15f629ea2a30.jpg","invisible":false},"created_at":"2020-10-28T04:52:20.269955007Z"},"duration":"95.55ms"}
> 2020-10-27 21:52:19.495 31310-32104/ai.zira.employee I/Chat:Http: <-- END HTTP (726-byte body)
> 2020-10-27 21:52:19.495 31310-31662/ai.zira.employee I/Chat:Events: {"type":"message.read","cid":"messaging:!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY","channel_id":"!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY","channel_type":"messaging","user":{"id":"enc-ZW5jLVZGZHdibVZCUFQwPS1lbmM","role":"user","created_at":"2020-09-25T05:11:59.666842Z","updated_at":"2020-10-28T04:52:09.223126Z","last_active":"2020-10-28T04:45:47.969832Z","banned":false,"online":false,"teams":["enc-ZW5jLVZHMXdUbEJSUFQwPS1lbmM","enc-ZW5jLVZEQlNRbEJSUFQwPS1lbmM"],"name":"Xiachao Yang","devices":null,"image":"https://z-public-storage.s3.amazonaws.com/profile_pic/cd323a13-31a9-452f-ab12-15f629ea2a30.jpg","invisible":false},"created_at":"2020-10-28T04:52:20.269955007Z"}
> 2020-10-27 21:52:19.495 31310-32104/ai.zira.employee W/i.zira.employe: Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
> 2020-10-27 21:52:19.556 31310-32109/ai.zira.employee I/System.out: updateReads for current user to Tue Oct 27 21:52:20 PDT 2020 on channel messaging:!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY
> 2020-10-27 21:52:19.557 31310-32109/ai.zira.employee I/Chat:ChatDomain QueryChannelsController: received channel event NotificationMarkReadEvent(type=notification.mark_read, createdAt=Tue Oct 27 21:52:20 PDT 2020, user=User(id=enc-ZW5jLVZGZHdibVZCUFQwPS1lbmM, role=user, invisible=false, banned=false, devices=[], online=false, createdAt=Thu Sep 24 22:11:59 PDT 2020, updatedAt=Tue Oct 27 21:52:09 PDT 2020, lastActive=Tue Oct 27 21:45:47 PDT 2020, totalUnreadCount=0, unreadChannels=0, unreadCount=0, mutes=[], teams=[enc-ZW5jLVZHMXdUbEJSUFQwPS1lbmM, enc-ZW5jLVZEQlNRbEJSUFQwPS1lbmM], channelMutes=[], extraData={image=https://z-public-storage.s3.amazonaws.com/profile_pic/cd323a13-31a9-452f-ab12-15f629ea2a30.jpg, name=Xiachao Yang}), cid=messaging:!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY, channelType=messaging, channelId=!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY, watcherCount=null, totalUnreadCount=0, unreadChannels=0)
> 2020-10-27 21:52:19.559 31310-31310/ai.zira.employee I/Chat:MessageListView: no Scroll no new message
> 2020-10-27 21:52:19.567 31310-32114/ai.zira.employee I/System.out: updateReads for current user to Tue Oct 27 21:52:20 PDT 2020 on channel messaging:!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY
> 2020-10-27 21:52:19.568 31310-32114/ai.zira.employee I/Chat:ChatDomain QueryChannelsController: received channel event NotificationMarkReadEvent(type=notification.mark_read, createdAt=Tue Oct 27 21:52:20 PDT 2020, user=User(id=enc-ZW5jLVZGZHdibVZCUFQwPS1lbmM, role=user, invisible=false, banned=false, devices=[], online=false, createdAt=Thu Sep 24 22:11:59 PDT 2020, updatedAt=Tue Oct 27 21:52:09 PDT 2020, lastActive=Tue Oct 27 21:45:47 PDT 2020, totalUnreadCount=0, unreadChannels=0, unreadCount=0, mutes=[], teams=[enc-ZW5jLVZHMXdUbEJSUFQwPS1lbmM, enc-ZW5jLVZEQlNRbEJSUFQwPS1lbmM], channelMutes=[], extraData={image=https://z-public-storage.s3.amazonaws.com/profile_pic/cd323a13-31a9-452f-ab12-15f629ea2a30.jpg, name=Xiachao Yang}), cid=messaging:!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY, channelType=messaging, channelId=!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY, watcherCount=null, totalUnreadCount=0, unreadChannels=0)
> 2020-10-27 21:52:19.570 31310-31310/ai.zira.employee I/Chat:MessageListView: no Scroll no new message
> 2020-10-27 21:52:19.570 31310-32109/ai.zira.employee I/System.out: updateReads for current user to Tue Oct 27 21:52:20 PDT 2020 on channel messaging:!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY
> 2020-10-27 21:52:19.571 31310-32109/ai.zira.employee I/Chat:ChatDomain QueryChannelsController: received channel event MessageReadEvent(type=message.read, createdAt=Tue Oct 27 21:52:20 PDT 2020, user=User(id=enc-ZW5jLVZGZHdibVZCUFQwPS1lbmM, role=user, invisible=false, banned=false, devices=[], online=false, createdAt=Thu Sep 24 22:11:59 PDT 2020, updatedAt=Tue Oct 27 21:52:09 PDT 2020, lastActive=Tue Oct 27 21:45:47 PDT 2020, totalUnreadCount=0, unreadChannels=0, unreadCount=0, mutes=[], teams=[enc-ZW5jLVZHMXdUbEJSUFQwPS1lbmM, enc-ZW5jLVZEQlNRbEJSUFQwPS1lbmM], channelMutes=[], extraData={image=https://z-public-storage.s3.amazonaws.com/profile_pic/cd323a13-31a9-452f-ab12-15f629ea2a30.jpg, name=Xiachao Yang}), cid=messaging:!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY, channelType=messaging, channelId=!members-tWXPWlk5TjnvB0ljfHzQT1WXVjHFYq1mqsw6nAUsqZY, watcherCount=null)
> 2020-10-27 21:52:19.573 31310-31310/ai.zira.employee I/Chat:MessageListView: no Scroll no new message
> 2020-10-27 21:52:19.646 31310-31324/ai.zira.employee I/i.zira.employe: Background concurrent copying GC freed 88231(4536KB) AllocSpace objects, 2(40KB) LOS objects, 24% free, 18MB/24MB, paused 469us total 129.274ms

**Comment by tschellenbach** [comment]
Do you have any additional details on how to replicate this? Can you
replicate it on the sample app? (develop branch)

**Comment by pixnbit** [comment]
Yes, replicated with the sample app. I think it's improved meaning sometimes messages got marked as read, before I never saw a message got marked.

[Our app](https://drive.google.com/file/d/1JoeUVbXYOwJ4vqGALAzXq6YFBQaWTJwX/view?usp=sharing)

[Sample app](https://drive.google.com/file/d/1koaMZMNUhG0r947gj5wtO_kJOzBW6kAm/view?usp=sharing), with three different users logged, sometimes messages are marked and sometimes not. (during which there's one message not delivered, the phone in the middle)

**Comment by tschellenbach** [comment]
Can you describe what doesn't work for the read state? Your first message was about the latest message, but I think the video describes an issue with read state?

**Comment by pixnbit** [comment]
Oh! I filed too many tickets I lost track, you're correct. Now the issue is the read state. The issue was the unread state of a message do not become read(bold to normal text style)

**Comment by tschellenbach** [comment]
Alright so 2 new issues here:
- one of the phones somehow doesn't receive an event for the new message... @tbarbugli and @JcMinarro see above
- read state doesn't seem to update correctly, cause unknown

**Comment by carterhudson** [comment]
Hi @pixnbit - would try to replicate the issue with using `com.github.GetStream:stream-chat-android:fix_stuck_unread_state-SNAPSHOT` and let me know if the issue persists?

**Comment by pixnbit** [comment]
I tried, and it indeed fixed! Works.

**Comment by JcMinarro** [comment]
Hi @pixnbit 
This patch is not merged yet, @carterhudson is completing it and will create a PR with the new solution.
It will be ready on the next version that will be released soon, probably today EOD or tomorrow
