### ISSUE TITLE
QuerySort not working when called first time

### ISSUE THREAD

**Issue by bibibilu** [GetStream/stream-chat-android#835]
I am using  QuerySort<Channel>().desc("last_message_at") to sort group channels as following:

![image](https://user-images.githubusercontent.com/55115952/98609226-a6e47080-22a1-11eb-9201-36081e57d13d.png)

However, this does not work properly when the view is first time created. Seems like it does not work until I refresh the view to call it again.

![30esw-lakna](https://user-images.githubusercontent.com/55115952/98610178-e744ee00-22a3-11eb-9caf-cc1772545228.gif)

**Comment by bibibilu** [comment]
One more issue related: the unread channel does not pop on the top while new message received. 
```
val sort = QuerySort<Channel>().desc("last_updated")
ChatDomain.instance().useCases.queryChannels(filterGroup, sort, 100).execute().data().channels
          .observe(viewLifecycleOwner, androidx.lifecycle.Observer {
            if (it.isEmpty()) {
              binding.groupExpandArrow.visibility = View.GONE
              binding.groupChannelsEmptyView.visibility = View.VISIBLE
            } else {
              binding.groupChannelsView.setHasFixedSize(false)
              binding.groupChannelsView.setChannels(it.filter { it.hidden == false })
              binding.groupChannelsView.setViewHolderFactory(myChannelsViewHolderFactory)
              binding.groupExpandArrow.visibility = View.VISIBLE
            }
            binding.groupChannelsLoadingView.visibility = View.GONE
          })
```
![x697x-ohqy0](https://user-images.githubusercontent.com/55115952/98750816-b7fdb200-2373-11eb-8d83-825b2b5370ec.gif)

**Comment by ogkuzmin** [comment]
@bibibilu Hello! Thank you for submitting this issue! We have fixed it in our codebase but haven't released it yet! The new version is going to be released this week or at the beginning of the next one. Please, wait for it and check that it works for you.

**Comment by tschellenbach** [comment]
4.4.2 has been released, @bibibilu did this fix your issue?

**Comment by bibibilu** [comment]
Hello! The sort still not works and the channel dates disappear at the beginning.
![1096](https://user-images.githubusercontent.com/55115952/99450073-1a573500-28d5-11eb-97da-1fee99755a25.gif)

**Comment by tschellenbach** [comment]
Thanks for letting us know, @ogkuzmin will investigate

**Comment by bibibilu** [comment]
oh and in addition, channel with new message does not pop up to the top as well. @ogkuzmin

**Comment by ogkuzmin** [comment]
Let's figure out with QuerySort. The API has changed a little bit, for your case you can use any of the following ways:
``` kotlin
val sort: QuerySort<Channel> = QuerySort.desc("last_message_at")
`
```kotlin
val sort: QuerySort<Channel> = QuerySort.desc(Channel::lastMessageAt)
`
```kotlin
val sort = QuerySort<Channel>().desc(Channel::lastMessageAt)
`

Your variant is good for sorting based on a custom property. Could you check this?

**Comment by ogkuzmin** [comment]
About the second problem (channels with new messages don't move up). I've repeated it and will try to fix it.

**Comment by ogkuzmin** [comment]
@bibibilu Second problem was fixed, new version with the fix will be available soon. We'll inform you!

**Comment by bibibilu** [comment]
@ogkuzmin Thanks for informing! For the query sort, yes, both querysort by "last_update" and by "last_message_at" is correct, but they only work after the page is refreshed.

**Comment by ogkuzmin** [comment]
@bibibilu Did you tried any of this?
``` kotlin
val sort: QuerySort<Channel> = QuerySort.desc("last_message_at")
val sort: QuerySort<Channel> = QuerySort.desc(Channel::lastMessageAt)
val sort = QuerySort<Channel>().desc(Channel::lastMessageAt)
```

**Comment by bibibilu** [comment]
@ogkuzmin Wow, I just fond sorting works properly now. 
So issue remain are
1. invisible channel date
2. new message not moving up
3. In addition, there is some issue related to the channel unread count. It seems inconsistent as the following video shows. And now the channel unread count always show 1. The unread count is observed in my customized ChannelViewHolderFactory. Do you have any idea what is going wrong here? 
```
ChannelListItemViewHolder holder = new ChannelListItemViewHolder(view) {
      @Override
      public void bind(Context context, @NonNull Channel channel, int position, @Nullable ChannelItemPayloadDiff diff) {
        super.bind(context, channel, position, diff);
        LifecycleOwner lifecycleOwner = (LifecycleOwner) itemView.getContext();
        ChatDomain.instance().getTotalUnreadCount().observe(lifecycleOwner, (Observer<Integer>) integer -> {
          TextView count = view.findViewById(R.id.channelUnreadCountTextView);
          unreadBadge.setVisibility(channel.getUnreadCount() == 0 ? View.GONE : View.VISIBLE);
          count.setText(channel.getUnreadCount() < 100 ? String.valueOf(channel.getUnreadCount()) : "...");
        });
      }
    };
```

![jt2wp-6vxz9](https://user-images.githubusercontent.com/55115952/99870544-a775e480-2b88-11eb-8bc4-8836531cf3d7.gif)

**Comment by tschellenbach** [comment]
Our backend team and Carter are working on issue number 3 at the moment.

**Comment by JcMinarro** [comment]
Issue 1 and 2 should be fixed on #897

**Comment by JcMinarro** [comment]
Hello @bibibilu 

@carterhudson has been working on 3 and it is fixed now on the [last version](https://github.com/GetStream/stream-chat-android/releases/latest)
